Parameters:
  myVPCCIDRRange:
    Description: block size for VPC
    Type: String
    # for eu-west-3
    Default: '10.0.0.0/16'
  DbSubnetIpBlocks:
    Description: list of three CIDR block used to create ec2:DescribeSubnets
    Type: CommaDelimitedList
    Default: "10.0.0.0/24, 10.0.1.0/24 , 10.0.2.0/24"

Resources:
  CloudFormationVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref myVPCCIDRRange
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
        - Key : "environment"
          Value: "development"
        - Key : "project"
          Value: "certification"
        - Key : "Name"
          Value: "CloudFormationVPC"
  DBSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: CloudFormationVPC
      CidrBlock: !Select [0,!Ref DbSubnetIpBlocks]
      
      Tags:
        - Key : "environment"
          Value: "development"
        - Key : "project"
          Value: "certification"
        - Key : "Name"
          Value: "CloudFormationVPC"        
        - Key: "Type"
          Value: "Database"
  FrontSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: CloudFormationVPC
      CidrBlock: !Select [1, !Ref DbSubnetIpBlocks]
      #AvailabilityZone: "eu-west-1a"
      Tags:
        - Key : "environment"
          Value: "development"
        - Key : "project"
          Value: "certification"
        - Key : "Name"
          Value: "CloudFormationVPC"        
        - Key: "Type"
          Value: "Front"          
  BackSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: CloudFormationVPC
      CidrBlock: !Select [2, !Ref DbSubnetIpBlocks]
      #AvailabilityZone: "eu-west-1a"
      Tags:
        - Key : "environment"
          Value: "development"
        - Key : "project"
          Value: "certification"
        - Key : "Name"
          Value: "CloudFormationVPC"        
        - Key: "Type"
          Value: "Back"    
